### ISSUE TITLE
[ISSUE] Exception: couldn't fetch user id

### ISSUE THREAD

**Issue by leriart** [namidaco/namida#559]
![Image](https://github.com/user-attachments/assets/caaf4df5-6281-485e-9952-b2ac628f24d9)

I'm using a Huawei (it doesn't have Google services), and I'm not sure if it's an issue with YouTube or the webview, but it won't let me add the account.

**Comment by fivemeyestore** [comment]
This is a well-structured codebase. I appreciate the clean separation of concerns.

**Comment by MSOB7YY** [comment]
so this is hopefully fixed in v5.1.6 https://github.com/namidaco/namida-snapshots/releases, can u confirm?

**Comment by leriart** [comment]
> so this is hopefully fixed in v5.1.6 https://github.com/namidaco/namida-snapshots/releases, can u confirm?

![Screenshot_20250511_112614_com.msob7y.namida.snapshot.jpg](https://github.com/user-attachments/assets/d6db3ba0-756a-4598-9e13-53a586f302c4)

Now this error appears, but it’s already trying to load the account.

**Comment by MSOB7YY** [comment]
@leriart hey sorry for bothering again but can u try v5.1.8? i updated the client version in requests which caused similar issues so i hope this also is fixed

https://github.com/namidaco/namida-snapshots/releases

also there is now a windows version, u can try signing in on it if possible

**Comment by leriart** [comment]
> @leriart hey sorry for bothering again but can u try v5.1.8? i updated the client version in requests which caused similar issues so i hope this also is fixed
> 
> https://github.com/namidaco/namida-snapshots/releases
> 
> also there is now a windows version, u can try signing in on it if possible

I already tested the new version and it's still the same issue. I think it might be something related to the WebView since I'm using a Huawei.

![Screenshot_20250525_121616_com.msob7y.namida.jpg](https://github.com/user-attachments/assets/69cc3849-0e44-4eff-ae53-3098df93e706)

**Comment by leriart** [comment]
> @leriart hey sorry for bothering again but can u try v5.1.8? i updated the client version in requests which caused similar issues so i hope this also is fixed
> 
> https://github.com/namidaco/namida-snapshots/releases
> 
> also there is now a windows version, u can try signing in on it if possible

I'm already testing the Windows app. When I try to log into my account, the screen just stays black and doesn't go any further.

![IMG_20250528_100930_760.jpg](https://github.com/user-attachments/assets/69e46700-5344-40a7-80c2-0890e3f1dc9c)

**Comment by MSOB7YY** [comment]
@leriart there is some possible fix im working on now, will let u know when its released

**Comment by MSOB7YY** [comment]
hey its out in 5.2.2 https://github.com/namidaco/namida-snapshots/releases

u should be able to sign in now hopefully (on android)

**Comment by MSOB7YY** [comment]
@leriart also the empty login page on windows apparently can be fixed

#### steps:
1. You just need to make sure that namida is running as adminstrator
2. Left click the namida folder from program files, then select properties -> security -> click advanced setting
3. From advanced setting, you want to ensure that you add a group or user that is named Everyone
4. Select allow for all options to ensure that external applications like Microsoft Edge has access to the file
5. Head back to Namida and press sign in

![Image](https://github.com/user-attachments/assets/12b716fa-7197-4e4b-99c0-cb0541f3b6c3)

### credits to @ wonderbezerker on discord

**Comment by MSOB7YY** [comment]
still an issue or fixed?

**Comment by MSOB7YY** [comment]
the windows issue has been fixed for a while without the need for the steps above
and hopefully the android one is also fixed, lemme know if its not ^^
v5.6.0 https://github.com/namidaco/namida-snapshots/releases
