### ISSUE TITLE
[BUG] Indexer gets stuck while processing Non-English Titles

### ISSUE THREAD

**Issue by 010101-sans** [namidaco/namida#657]
After starting re-indexing, the Indexer gets stuck while processing Non-English Titles (See screenshot)

![Image](https://github.com/user-attachments/assets/012f06bd-f1f1-487e-b309-69df2e461edd)

## Expected Behavior
Should process all titles

## Steps to Reproduce
Start re-indexing (Assuming you have an existing non English title, I've tested with only Japanese)

## Logs

(Repeats a few times)
│ Invalid argument: Cannot complete a future with itself: Instance of 'Future<AudioPlayerPlatform>'
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   Future._chainCoreFuture (dart:async/future_impl.dart:664)
│ #1   Future._chainFuture (dart:async/future_impl.dart:819)
│ #2   Future._asyncCompleteUnchecked (dart:async/future_impl.dart:785)
│ #3   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ ArgumentError

**Comment by MSOB7YY** [comment]
i doubt it's caused by non ascii characters, can u try copying and renaming them? or send 1-2 files to test

**Comment by 010101-sans** [comment]
Sent to you. Check Discord.
Put them in a folder -> include that folder -> re-index

**Comment by 010101-sans** [comment]
To add more info, when it's stuck at 1% for Japanese titles I force stop the app, then re-index again

It gets stuck at 33% again at another Japanese titles, force stop and re-index again 

Then it gets stuck on 67% at another Japanese titles again, I then force stop the app again, re-index again then it goes to 100% after all non-English or semi-non-English title are processed (or skipped, I'm not sure due to force stop)

Edit: just recalled that once after force stop, the app was stuck on start up itself, so had clear app data and restore the latest backup

**Comment by MSOB7YY** [comment]
it should be fixed in v5.4.7 https://github.com/namidaco/namida-snapshots/releases
can u verify and lemme know ?

**Comment by 010101-sans** [comment]
Unfortunately, it is still not working. 

Attempt 1 :

https://github.com/user-attachments/assets/fc57d2bb-4bb5-440a-9d06-83f6410bd329

Attempt 2 :

![Screenshot_20251115_230443.jpg](https://github.com/user-attachments/assets/e59b0e41-57e9-4408-a7a8-dae98fd87319)

Attempt 3 :

![Screenshot_20251115_230132.jpg](https://github.com/user-attachments/assets/4e04a5f4-f686-4c02-9e05-89c0d9068631)

Note I : 
After every indexing attempt gets stuck -

**Option A**
- If I force stop the app, and restart indexing, it skips those songs and index more songs and gets stuck again. 
- It takes 3-4 force stops and reindexing to reach 100%

**Option B**
- If I clear app data and restart indexing, it gets stuck again. 

Note II :
Indexer works flawlessly on windows. It gets stuck only in Android.

**Comment by MSOB7YY** [comment]
the beta v5.4.7 is still building sry 😭 wait few minutes
https://github.com/namidaco/namida/actions/workflows/dart.yml

**Comment by 010101-sans** [comment]
The latest v5.4.7 beta fixed the indexer, confirmed. It processed all non-english titles flawlessly without getting stuck. Thank you dev.
